# Generated by Django 5.2.4 on 2025-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('places', models.IntegerField(default=2)),
                ('price', models.IntegerField(default=2500)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room_type', models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=20)),
            ],
        ),
    ]
